from __future__ import annotations

import json
import re
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Iterable


PAGE_RE = re.compile(r"\[page\s+(\d+)\]", re.IGNORECASE)
QUANTITY_RE = re.compile(r"\d|克|个|棵|根|只|片|勺|匙|毫升|适量|少许|各|g|ml", re.IGNORECASE)
PUNCT_RE = re.compile(r"[，。：；、,.!！？?]")
NOISE_LINES = {
    "CMenu",
    "Menu",
    "家常菜精选265例",
}
FIELD_MARKERS = {"原料", "调料", "制作方法", "小提示"}


@dataclass(frozen=True)
class RecipeRecord:
    dish_name: str
    ingredients: str
    seasonings: str
    steps: str
    tips: str
    pages: list[int]
    source: str
    source_type: str
    category: str = ""


@dataclass(frozen=True)
class RefinedRecipeChunk:
    chunk_id: str
    source: str
    source_type: str
    text: str
    title: str
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def refine_recipe_chunks(raw_chunks: Iterable[dict[str, Any]], output_prefix: str = "recipe") -> list[RefinedRecipeChunk]:
    raw_list = list(raw_chunks)
    text = reconstruct_ocr_text(raw_list)
    first = raw_list[0] if raw_list else {}
    records = extract_recipe_records(
        text=text,
        source=str(first.get("source", "")),
        source_type=str(first.get("source_type", "pdf")),
    )
    return records_to_chunks(records, output_prefix=output_prefix)


def reconstruct_ocr_text(raw_chunks: list[dict[str, Any]]) -> str:
    ordered = sorted(
        raw_chunks,
        key=lambda row: (
            int(row.get("start_char", 0)),
            int(row.get("end_char", 0)),
            str(row.get("chunk_id", "")),
        ),
    )
    parts = []
    last_end = 0
    for row in ordered:
        text = str(row.get("text", ""))
        start = int(row.get("start_char", last_end))
        end = int(row.get("end_char", start + len(text)))
        overlap = max(0, last_end - start)
        parts.append(text[overlap:])
        last_end = max(last_end, end)
    return "\n".join(part for part in parts if part.strip())


def extract_recipe_records(text: str, source: str, source_type: str) -> list[RecipeRecord]:
    records = []
    for page_number, page_text in iter_pages(text):
        lines = clean_page_lines(page_text)
        if not lines:
            continue
        page_tips = extract_tip_pairs(lines)
        category = infer_page_category(lines)
        for recipe in extract_page_recipes(lines, page_number, source, source_type, page_tips, category):
            records.append(recipe)
    return dedupe_records(records)


def iter_pages(text: str) -> Iterable[tuple[int, str]]:
    matches = list(PAGE_RE.finditer(text))
    if not matches:
        yield 0, text
        return
    for index, match in enumerate(matches):
        start = match.end()
        end = matches[index + 1].start() if index + 1 < len(matches) else len(text)
        yield int(match.group(1)), text[start:end]


def clean_page_lines(text: str) -> list[str]:
    lines = []
    for raw_line in text.splitlines():
        line = normalize_line(raw_line)
        if not line:
            continue
        if line in NOISE_LINES:
            continue
        if line.isdigit() and len(line) <= 4:
            continue
        if looks_like_archive_line(line):
            continue
        lines.append(line)
    return dedupe_adjacent(lines)


def normalize_line(line: str) -> str:
    return re.sub(r"\s+", " ", line).strip()


def looks_like_archive_line(line: str) -> bool:
    lowered = line.lower()
    return any(
        marker in lowered
        for marker in (
            "document generated by anna",
            "pdg_main_pages_found",
            "after_pdg2pic_conversion",
            "sha256",
            "filesize",
        )
    )


def extract_page_recipes(
    lines: list[str],
    page_number: int,
    source: str,
    source_type: str,
    page_tips: dict[str, str],
    category: str,
) -> list[RecipeRecord]:
    material_indices = [index for index, line in enumerate(lines) if line == "原料"]
    records = []
    for offset, material_index in enumerate(material_indices):
        end = material_indices[offset + 1] if offset + 1 < len(material_indices) else len(lines)
        block = lines[material_index:end]
        record = parse_recipe_block(block, lines, material_index, page_number, source, source_type, page_tips, category)
        if record is not None:
            records.append(record)
    return records


def parse_recipe_block(
    block: list[str],
    page_lines: list[str],
    material_index: int,
    page_number: int,
    source: str,
    source_type: str,
    page_tips: dict[str, str],
    category: str,
) -> RecipeRecord | None:
    if "调料" not in block or "制作方法" not in block:
        return None
    dish_name = infer_dish_name(block, page_lines, material_index)
    if not dish_name:
        return None

    ingredients = collect_between(block, "原料", "调料", skip={dish_name})
    dish_name = correct_dish_name_from_tips(dish_name, ingredients, page_tips)
    seasonings = collect_between(block, "调料", "制作方法", skip={dish_name})
    steps_end = "小提示" if "小提示" in block else None
    steps = collect_between(block, "制作方法", steps_end, skip={dish_name})
    inline_tips = extract_inline_tip_for_dish(block, dish_name)
    tips = page_tips.get(dish_name, "") or inline_tips

    if len(ingredients) < 2 or len(steps) < 8:
        return None
    return RecipeRecord(
        dish_name=dish_name,
        ingredients=ingredients,
        seasonings=seasonings,
        steps=steps,
        tips=tips,
        pages=[page_number] if page_number else [],
        source=source,
        source_type=source_type,
        category=category,
    )


def infer_dish_name(block: list[str], page_lines: list[str], material_index: int) -> str:
    try:
        material_offset = block.index("原料")
    except ValueError:
        material_offset = 0

    for candidate in block[material_offset + 1 : material_offset + 5]:
        if is_title_like(candidate):
            return candidate

    for candidate in reversed(page_lines[max(0, material_index - 5) : material_index]):
        if is_title_like(candidate):
            return candidate

    for marker in ("小提示", "制作方法", "调料"):
        if marker in block:
            marker_index = block.index(marker)
            for candidate in block[max(0, marker_index - 4) : marker_index + 5]:
                if is_title_like(candidate):
                    return candidate
    return ""


def collect_between(block: list[str], start_marker: str, end_marker: str | None, skip: set[str] | None = None) -> str:
    skip = skip or set()
    try:
        start = block.index(start_marker) + 1
    except ValueError:
        return ""
    if end_marker is None:
        end = len(block)
    else:
        try:
            end = block.index(end_marker, start)
        except ValueError:
            end = len(block)
    values = []
    for line in block[start:end]:
        if line in FIELD_MARKERS or line in skip:
            continue
        if is_probable_next_recipe_title(line):
            continue
        values.append(line)
    return normalize_field_text(values)


def normalize_field_text(lines: list[str]) -> str:
    text = "".join(join_recipe_lines(lines))
    text = re.sub(r"\s+", " ", text).strip()
    return text


def join_recipe_lines(lines: list[str]) -> list[str]:
    result = []
    for line in lines:
        if not result:
            result.append(line)
            continue
        if should_join_without_space(result[-1], line):
            result[-1] = result[-1] + line
        else:
            result.append(line)
    return result


def should_join_without_space(previous: str, current: str) -> bool:
    if previous.endswith(("，", "、", "；", "：", "。", ".", ",")):
        return False
    if current.startswith(("，", "、", "；", "。", ".", ",")):
        return True
    return bool(re.search(r"[\u4e00-\u9fff]$", previous) and re.match(r"^[\u4e00-\u9fff]", current))


def extract_tip_pairs(lines: list[str]) -> dict[str, str]:
    tips: dict[str, str] = {}
    tip_starts = [index for index, line in enumerate(lines) if line == "小提示"]
    for tip_start in tip_starts:
        current_title = ""
        current_lines: list[str] = []
        for line in lines[tip_start + 1 :]:
            if line == "原料":
                break
            if line in {"调料", "制作方法", "小提示"}:
                continue
            if is_title_like(line):
                if current_title and current_lines:
                    tips[current_title] = normalize_field_text(current_lines)
                current_title = line
                current_lines = []
            elif current_title:
                current_lines.append(line)
        if current_title and current_lines:
            tips[current_title] = normalize_field_text(current_lines)
    return tips


def correct_dish_name_from_tips(dish_name: str, ingredients: str, page_tips: dict[str, str]) -> str:
    if not page_tips:
        return dish_name
    candidates = list(page_tips)
    if dish_name in page_tips and len(dish_name) >= 3:
        return dish_name
    scored = []
    for candidate in candidates:
        overlap = ingredient_title_overlap(candidate, ingredients)
        if candidate in ingredients:
            overlap += 2
        if dish_name and dish_name in candidate:
            overlap += 1
        scored.append((overlap, len(candidate), candidate))
    scored.sort(reverse=True)
    if scored and scored[0][0] > 0:
        return scored[0][2]
    return dish_name


def ingredient_title_overlap(title: str, ingredients: str) -> int:
    chars = [char for char in title if "\u4e00" <= char <= "\u9fff"]
    return sum(1 for char in set(chars) if char in ingredients)


def extract_inline_tip_for_dish(block: list[str], dish_name: str) -> str:
    if "小提示" not in block:
        return ""
    tips = extract_tip_pairs(block)
    return tips.get(dish_name, "")


def infer_page_category(lines: list[str]) -> str:
    for line in lines[:12]:
        if line in {"凉菜", "热菜", "汤煲", "主食", "素菜", "荤菜"}:
            return line
    return ""


def is_title_like(line: str) -> bool:
    if not line or len(line) > 18:
        return False
    if line in FIELD_MARKERS or line in NOISE_LINES:
        return False
    if QUANTITY_RE.search(line):
        return False
    if PUNCT_RE.search(line):
        return False
    if line.startswith("此菜"):
        return False
    return bool(re.search(r"[\u4e00-\u9fff]", line))


def is_probable_next_recipe_title(line: str) -> bool:
    return is_title_like(line)


def dedupe_records(records: list[RecipeRecord]) -> list[RecipeRecord]:
    result = []
    seen = set()
    for record in records:
        key = (record.dish_name, tuple(record.pages), record.ingredients[:30], record.steps[:30])
        if key in seen:
            continue
        seen.add(key)
        result.append(record)
    return result


def records_to_chunks(records: list[RecipeRecord], output_prefix: str = "recipe") -> list[RefinedRecipeChunk]:
    chunks = []
    for index, record in enumerate(records):
        text = format_recipe_record(record)
        stem = Path(record.source).stem or output_prefix
        chunks.append(
            RefinedRecipeChunk(
                chunk_id=f"{stem}-recipe-{index:04d}",
                source=record.source,
                source_type=record.source_type,
                text=text,
                title=record.dish_name,
                metadata={
                    "dish_name": record.dish_name,
                    "ingredients": record.ingredients,
                    "seasonings": record.seasonings,
                    "tips": record.tips,
                    "pages": record.pages,
                    "page_start": min(record.pages) if record.pages else None,
                    "page_end": max(record.pages) if record.pages else None,
                    "category": record.category,
                    "section": "full_recipe",
                    "has_ingredients": bool(record.ingredients),
                    "has_steps": bool(record.steps),
                    "ocr": record.source_type == "pdf",
                },
            )
        )
    return chunks


def format_recipe_record(record: RecipeRecord) -> str:
    lines = [
        f"菜名：{record.dish_name}",
        f"原料：{record.ingredients}",
    ]
    if record.seasonings:
        lines.append(f"调料：{record.seasonings}")
    lines.append(f"制作方法：{record.steps}")
    if record.tips:
        lines.append(f"小提示：{record.tips}")
    if record.category:
        lines.append(f"分类：{record.category}")
    if record.pages:
        lines.append("来源页码：" + ",".join(str(page) for page in record.pages))
    return "\n".join(lines)


def load_jsonl(path: Path) -> list[dict[str, Any]]:
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def write_recipe_chunks_jsonl(chunks: Iterable[RefinedRecipeChunk], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        "\n".join(json.dumps(chunk.to_dict(), ensure_ascii=False) for chunk in chunks) + "\n",
        encoding="utf-8",
    )


def dedupe_adjacent(lines: list[str]) -> list[str]:
    result = []
    previous = None
    for line in lines:
        if line != previous:
            result.append(line)
        previous = line
    return result
