from __future__ import annotations

import zipfile
from pathlib import Path

from app.services import document_chunking
from app.services.document_chunking import (
    ChunkingConfig,
    OcrConfig,
    chunk_document,
    chunk_text,
    looks_like_archive_metadata,
    should_use_ocr,
    strip_html,
)


def test_chunk_text_uses_overlap_and_keeps_metadata() -> None:
    text = "第一段介绍系统目标。第二段介绍索引流程。第三段介绍检索流程。第四段介绍生成流程。"
    chunks = chunk_text(
        text,
        source="manual.txt",
        source_type="txt",
        config=ChunkingConfig(chunk_size=28, chunk_overlap=8, min_chunk_size=1),
        metadata={"doc_id": "manual"},
    )

    assert len(chunks) >= 2
    assert chunks[0].chunk_id == "manual-0000"
    assert chunks[0].metadata["doc_id"] == "manual"
    assert "索引流程" in "\n".join(chunk.text for chunk in chunks)
    assert chunks[1].text[:8].strip()


def test_strip_html_removes_script_and_keeps_visible_text() -> None:
    raw = """
    <html><head><style>.x{color:red}</style><script>alert(1)</script></head>
    <body><h1>菜谱文档</h1><p>番茄炒蛋适合快手晚餐。</p></body></html>
    """

    text = strip_html(raw)

    assert "alert" not in text
    assert "菜谱文档" in text
    assert "番茄炒蛋" in text


def test_chunk_document_reads_docx() -> None:
    artifact_dir = Path("data/processed/test_document_chunking")
    artifact_dir.mkdir(parents=True, exist_ok=True)
    docx_path = artifact_dir / "recipe.docx"
    xml = """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
      <w:body>
        <w:p><w:r><w:t>第一段：番茄炒蛋需要番茄和鸡蛋。</w:t></w:r></w:p>
        <w:p><w:r><w:t>第二段：先炒鸡蛋，再加入番茄。</w:t></w:r></w:p>
      </w:body>
    </w:document>
    """
    with zipfile.ZipFile(docx_path, "w") as archive:
        archive.writestr("word/document.xml", xml)

    chunks = chunk_document(docx_path, config=ChunkingConfig(chunk_size=120, chunk_overlap=20))

    assert len(chunks) == 1
    assert chunks[0].source_type == "docx"
    assert "番茄炒蛋" in chunks[0].text


def test_should_use_ocr_when_text_layer_is_too_small() -> None:
    assert should_use_ocr("很少的文字", OcrConfig(enabled=True, min_extracted_chars=1000))
    assert not should_use_ocr("很少的文字", OcrConfig(enabled=False, min_extracted_chars=1000))
    assert not should_use_ocr("足够长的文字" * 200, OcrConfig(enabled=True, min_extracted_chars=100))
    assert should_use_ocr("足够长的文字" * 200, OcrConfig(enabled=True, force=True))


def test_archive_metadata_forces_ocr() -> None:
    text = """
    Document generated by Anna's Archive around 2023-2024.
    "pdg_main_pages_found": 152,
    "after_pdg2pic_conversion": {}
    """

    assert looks_like_archive_metadata(text)
    assert should_use_ocr(text, OcrConfig(enabled=True, min_extracted_chars=10))
