from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parent.parent
if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Import document RAG chunks and metadata into MySQL while keeping the FAISS index on disk."
    )
    parser.add_argument(
        "--metadata",
        default=str(ROOT_DIR / "data" / "processed" / "new_pdf_recipe_metadata.json"),
        help="Path to document FAISS metadata JSON generated by build_document_index.py.",
    )
    parser.add_argument(
        "--metadata-dir",
        default=None,
        help="Batch mode: import metadata files from this directory.",
    )
    parser.add_argument(
        "--metadata-glob",
        default="*_recipe_metadata.json",
        help="Batch mode glob under --metadata-dir. Default: *_recipe_metadata.json",
    )
    parser.add_argument(
        "--index",
        default=str(ROOT_DIR / "data" / "processed" / "new_pdf_recipe.index"),
        help="Path to the local FAISS index file. The file is not imported; only its path is stored.",
    )
    parser.add_argument(
        "--index-name",
        default=None,
        help="Logical name used to group chunks and connect them to the local FAISS index.",
    )
    parser.add_argument(
        "--reset",
        action="store_true",
        help="Truncate document_indexes and document_chunks before importing.",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=500,
        help="Rows inserted per MySQL executemany batch. Default: 500",
    )
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="Batch mode: keep importing later metadata files when one file fails.",
    )
    parser.add_argument(
        "--skip-missing-index",
        action="store_true",
        help="Batch mode: skip metadata files whose inferred FAISS index file does not exist.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Validate metadata and print counts without connecting to MySQL.",
    )
    args = parser.parse_args()

    if args.metadata_dir:
        return run_batch(args)

    summary = build_import_summary(Path(args.metadata), Path(args.index), args.index_name)
    if args.dry_run:
        print(json.dumps({"dry_run": True, **summary}, ensure_ascii=False, indent=2))
        return 0

    counts, stats, target = import_one(summary, reset=args.reset, batch_size=args.batch_size)
    print(f"mysql_import_target={target}")
    print(json.dumps({"imported": counts, "summary": summary, "database_stats": stats}, ensure_ascii=False, indent=2))
    return 0


def run_batch(args: argparse.Namespace) -> int:
    metadata_paths = sorted(path for path in Path(args.metadata_dir).glob(args.metadata_glob) if path.is_file())
    if not metadata_paths:
        raise ValueError(f"No metadata files found: {args.metadata_dir}/{args.metadata_glob}")

    if args.dry_run:
        results = []
        for metadata_path in metadata_paths:
            index_path = infer_index_path(metadata_path)
            if args.skip_missing_index and not index_path.exists():
                results.append({"metadata_path": str(metadata_path), "status": "skipped", "reason": "missing index"})
                continue
            results.append({"status": "ok", **build_import_summary(metadata_path, index_path, None)})
        print(json.dumps({"dry_run": True, "batch_total": len(results), "results": results}, ensure_ascii=False, indent=2))
        return 0

    from app.services.mysql_store import MySQLConfig, MySQLStore

    config = MySQLConfig.from_env()
    store = MySQLStore(config)
    store.ensure_schema()
    if args.reset:
        store.reset_document_tables()

    results = []
    for position, metadata_path in enumerate(metadata_paths, start=1):
        index_path = infer_index_path(metadata_path)
        if args.skip_missing_index and not index_path.exists():
            result = {"metadata_path": str(metadata_path), "status": "skipped", "reason": "missing index"}
            results.append(result)
            print(json.dumps({"batch_progress": f"{position}/{len(metadata_paths)}", **result}, ensure_ascii=False))
            continue
        try:
            summary = build_import_summary(metadata_path, index_path, None)
            counts = store.import_document_index(
                index_name=str(summary["index_name"]),
                index_path=str(summary["index_path"]),
                metadata_path=str(summary["metadata_path"]),
                metadata=load_metadata(metadata_path),
                batch_size=args.batch_size,
            )
            result = {"status": "ok", "imported": counts, "summary": summary}
        except Exception as exc:
            result = {"metadata_path": str(metadata_path), "status": "failed", "error": f"{type(exc).__name__}: {exc}"}
            if not args.continue_on_error:
                print(json.dumps({"batch_progress": f"{position}/{len(metadata_paths)}", **result}, ensure_ascii=False))
                raise
        results.append(result)
        print(json.dumps({"batch_progress": f"{position}/{len(metadata_paths)}", **result}, ensure_ascii=False))

    stats = store.stats()
    ok_count = sum(1 for row in results if row["status"] == "ok")
    skipped_count = sum(1 for row in results if row["status"] == "skipped")
    failed_count = sum(1 for row in results if row["status"] == "failed")
    print(f"mysql_import_target={config.host}:{config.port}/{config.database}")
    print(
        json.dumps(
            {
                "batch_total": len(results),
                "ok": ok_count,
                "skipped": skipped_count,
                "failed": failed_count,
                "database_stats": stats,
                "results": results,
            },
            ensure_ascii=False,
            indent=2,
        )
    )
    return 1 if failed_count else 0


def build_import_summary(metadata_path: Path, index_path: Path, index_name: str | None) -> dict[str, Any]:
    metadata = load_metadata(metadata_path)
    chunks = metadata.get("chunks") or []
    if not isinstance(chunks, list) or not chunks:
        raise ValueError(f"No chunks found in metadata: {metadata_path}")
    resolved_index_name = index_name or index_path.stem
    return {
        "index_name": resolved_index_name,
        "index_path": str(index_path),
        "metadata_path": str(metadata_path),
        "embedding_backend": metadata.get("embedding_backend"),
        "index_type": metadata.get("index_type"),
        "chunk_count": len(chunks),
    }


def import_one(summary: dict[str, Any], reset: bool, batch_size: int):
    from app.services.mysql_store import MySQLConfig, MySQLStore

    config = MySQLConfig.from_env()
    store = MySQLStore(config)
    try:
        store.ensure_schema()
        if reset:
            store.reset_document_tables()
        counts = store.import_document_index(
            index_name=str(summary["index_name"]),
            index_path=str(summary["index_path"]),
            metadata_path=str(summary["metadata_path"]),
            metadata=load_metadata(Path(str(summary["metadata_path"]))),
            batch_size=batch_size,
        )
        stats = store.stats()
    except Exception as exc:
        print(f"mysql_document_import_failed={type(exc).__name__}: {exc}")
        raise
    return counts, stats, f"{config.host}:{config.port}/{config.database}"


def infer_index_path(metadata_path: Path) -> Path:
    name = metadata_path.name
    if name.endswith("_metadata.json"):
        return metadata_path.with_name(name[: -len("_metadata.json")] + ".index")
    return metadata_path.with_suffix(".index")


def load_metadata(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Metadata file not found: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Metadata must be a JSON object: {path}")
    return data


if __name__ == "__main__":
    raise SystemExit(main())
